
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.VBox vbox1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label label2;

	private global::Gtk.Entry entry2;

	private global::Gtk.VBox vbox6;

	private global::Gtk.HBox hbox9;

	private global::Gtk.Label label6;

	private global::Gtk.Label label7;

	private global::Gtk.Label label8;

	private global::Gtk.HBox hbox10;

	private global::Gtk.SpinButton spinbutton3;

	private global::Gtk.SpinButton spinbutton4;

	private global::Gtk.SpinButton spinbutton5;

	private global::Gtk.Button button1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = "Интерполяция";
		this.Icon = global::Stetic.IconLoader.LoadIcon(this, "gtk-convert", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(15));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = "f(x) = ";
		this.hbox1.Add(this.label2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.entry2 = new global::Gtk.Entry();
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.Text = "Math.Sin(x) * x";
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '●';
		this.hbox1.Add(this.entry2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.entry2]));
		w3.Position = 1;
		this.vbox2.Add(this.hbox1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox();
		this.hbox9.Name = "hbox9";
		this.hbox9.Homogeneous = true;
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = "Первый узел";
		this.label6.Justify = ((global::Gtk.Justification)(2));
		this.hbox9.Add(this.label6);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label6]));
		w5.Position = 0;
		w5.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = "Шаг";
		this.label7.Justify = ((global::Gtk.Justification)(2));
		this.hbox9.Add(this.label7);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label7]));
		w6.Position = 1;
		w6.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.label8.LabelProp = "Кол-во узлов";
		this.label8.Justify = ((global::Gtk.Justification)(2));
		this.hbox9.Add(this.label8);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label8]));
		w7.Position = 2;
		w7.Fill = false;
		this.vbox6.Add(this.hbox9);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox9]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox();
		this.hbox10.Name = "hbox10";
		this.hbox10.Homogeneous = true;
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.spinbutton3 = new global::Gtk.SpinButton(-100D, 100D, 1D);
		this.spinbutton3.CanFocus = true;
		this.spinbutton3.Name = "spinbutton3";
		this.spinbutton3.Adjustment.PageIncrement = 10D;
		this.spinbutton3.ClimbRate = 1D;
		this.spinbutton3.Digits = ((uint)(2));
		this.spinbutton3.Numeric = true;
		this.spinbutton3.Value = 3D;
		this.hbox10.Add(this.spinbutton3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.spinbutton3]));
		w9.Position = 0;
		w9.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.spinbutton4 = new global::Gtk.SpinButton(-10D, 10D, 0.1D);
		this.spinbutton4.CanFocus = true;
		this.spinbutton4.Name = "spinbutton4";
		this.spinbutton4.Adjustment.PageIncrement = 1D;
		this.spinbutton4.ClimbRate = 0.1D;
		this.spinbutton4.Digits = ((uint)(2));
		this.spinbutton4.Numeric = true;
		this.spinbutton4.Value = 1D;
		this.hbox10.Add(this.spinbutton4);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.spinbutton4]));
		w10.Position = 1;
		w10.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.spinbutton5 = new global::Gtk.SpinButton(2D, 100D, 1D);
		this.spinbutton5.CanFocus = true;
		this.spinbutton5.Name = "spinbutton5";
		this.spinbutton5.Adjustment.PageIncrement = 10D;
		this.spinbutton5.ClimbRate = 1D;
		this.spinbutton5.Numeric = true;
		this.spinbutton5.Value = 4D;
		this.hbox10.Add(this.spinbutton5);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.spinbutton5]));
		w11.Position = 2;
		w11.Fill = false;
		w11.Padding = ((uint)(20));
		this.vbox6.Add(this.hbox10);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox10]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		this.vbox2.Add(this.vbox6);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox6]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = "Интерполировать";
		this.vbox2.Add(this.button1);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.button1]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		this.vbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 680;
		this.DefaultHeight = 583;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button1.Clicked += new global::System.EventHandler(this.OnButton1Clicked);
	}
}
